version: "3.8"

x-common-env: &common-env
  CYCLONEDDS_URI: >-
    <CycloneDDS><Domain><Discovery><MaxAutoParticipantIndex>1000</MaxAutoParticipantIndex></Discovery></Domain></CycloneDDS>
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
  ROS_DOMAIN_ID: "0"

services:
  turtlebot-gazebo:
    image: cinoderobotics/turtlebot4_navigation:kilted-amd64-v1.2.0
    container_name: ros2-turtlebot4-gazebo-kilted
    tty: True
    privileged: true  # needed for Gazebo GUI / hardware access
    network_mode: "host"

    environment:
      <<: *common-env
      DISPLAY: ${DISPLAY}
      ROS_DISTRO: kilted
      QT_X11_NO_MITSHM: "0"
      QT_QPA_PLATFORM: xcb

      # Gazebo rendering (GPU lidar needs this)
      GZ_RENDER_ENGINE: ogre
      GZ_GUI_CONFIG: ""
      vblank_mode: "0"
      MESA_LOADER_DRIVER_OVERRIDE: radeonsi
      LIBGL_DRI3_DISABLE: "0"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/shm:/dev/shm
      - ./scripts/route_example_launch.py:/opt/ros/kilted/share/nav2_simple_commander/route_example_launch.py:ro
      - ./turtlebot4_simulator/turtlebot4_gz_bringup/worlds/test.sdf:/opt/ros/kilted/share/nav2_minimal_tb4_sim/worlds/test.sdf:ro
      - ./turtlebot4_simulator/turtlebot4_gz_bringup/worlds/bot4House.sdf:/opt/ros/kilted/share/nav2_minimal_tb4_sim/worlds/bot4House.sdf:ro

      - ./turtlebot4/turtlebot4_navigation/maps/test.yaml:/opt/ros/kilted/share/nav2_bringup/maps/test.yaml:ro
      - ./turtlebot4/turtlebot4_navigation/maps/test.pgm:/opt/ros/kilted/share/nav2_bringup/maps/test.pgm:ro

      - ./turtlebot4/turtlebot4_navigation/maps/house.yaml:/opt/ros/kilted/share/nav2_bringup/maps/house.yaml:ro
      - ./turtlebot4/turtlebot4_navigation/maps/house.pgm:/opt/ros/kilted/share/nav2_bringup/maps/house.pgm:ro

      - ./turtlebot4/turtlebot4_navigation/maps/bot4House.yaml:/opt/ros/kilted/share/nav2_bringup/maps/bot4House.yaml:ro
      - ./turtlebot4/turtlebot4_navigation/maps/bot4House.pgm:/opt/ros/kilted/share/nav2_bringup/maps/bot4House.pgm:ro
      
      - ./graphs/depot_graph.geojson:/opt/ros/kilted/share/nav2_bringup/graphs/depot_graph.geojson:rw
      - ./graphs/warehouse_graph.geojson:/opt/ros/kilted/share/nav2_bringup/graphs/warehouse_graph.geojson:rw
      - ./graphs/house_graph.geojson:/opt/ros/kilted/share/nav2_bringup/graphs/house_graph.geojson:rw
      - ./graphs/bot4House_graph.geojson:/opt/ros/kilted/share/nav2_bringup/graphs/bot4House_graph.geojson:rw

    command: /bin/bash -c 'ros2 launch nav2_simple_commander route_example_launch.py use_keepout_zones:=False use_speed_zones:=False force_software_rendering:=True'
